apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
# nameSuffix: -production
commonLabels:
  environment: production
resources:
  - deployment.yaml
  - service.yaml
