apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-entry-gql-edge
  newTag: b061bb0c1ee1f4d5a869ecad5e0bc32d0762f3db # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
