apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-entry-gql-edge:a55b96841b7024ab66546e5fd1bfaaf0cb35fc21 # {"$ref":"#/definitions/io.k8s.cli.substitutions.image"}
