apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-entry-gql-edge
  newTag: 84837f3f2fd3b6c6dc99f98de7c0bb44d12061de # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
