apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-entry-gql-edge
  newTag: 0d0249de3aa517eceac0c437941c043517e0331c # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
