apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-web
  namespace: di
  labels:
    app: public-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-web
  template:
    metadata:
      labels:
        app: public-web
    spec:
      serviceAccountName: public-web
      containers:
      - name: public-web
        image: jasonblanchard/di-public-web
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: public-web-config
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
