apiVersion: v1
kind: Service
metadata:
  labels:
    app: public-web
  name: public-web
  namespace: di
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: public-web
  type: ClusterIP
