apiVersion: v1
kind: ConfigMap
metadata:
  name: di-entry-migrations
  namespace: di
  labels:
    app: di-entry-jobs
data:
  DB_USER: postgres
  DB_PASSWORD: changeme
  DB_HOST: di-entry-tf.cluster-cscliqw1dfil.us-east-1.rds.amazonaws.com
  DB_DATABASE: di
---
apiVersion: batch/v1
kind: Job
metadata:
  name: di-entry-migrations
  namespace: di
spec:
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-entry
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      serviceAccountName: entry
      containers:
      - image: jasonblanchard/di-entry:fbb4d023af4c3ff1bc3f578342d0bc9d77c576df # {"$ref":"#/definitions/io.k8s.cli.substitutions.image"}
        name: di-entry-migrations
        command:
        - npm
        - run
        - db:migrate:up
        envFrom:
        - configMapRef:
            name: di-entry-migrations
      restartPolicy: Never
