apiVersion: v1
kind: ConfigMap
metadata:
  name: di-entry-migrations
  namespace: di
  labels:
    app: di-entry-jobs
data:
  DB_USER: di
  DB_PASSWORD: vault:secret/data/di-entry/development/app#DB_PASSWORD
  DB_HOST: di-entry-psql
  DB_DATABASE: di_entry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: di-entry-migrations
  namespace: di
spec:
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-entry
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      serviceAccountName: di-entry
      containers:
      - image: jasonblanchard/di-entry:3512a0b027d7ea4b1f669249d62eaf49564ccb68 # {"$ref":"#/definitions/io.k8s.cli.substitutions.image"}
        name: di-entry-migrations
        command:
        - npm
        - run
        - db:migrate:up
        envFrom:
        - configMapRef:
            name: di-entry-migrations
      restartPolicy: Never
