apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
resources:
- sa.yaml
- deployment.yaml
images:
- name: jasonblanchard/di-entry
  newTag: latest
configMapGenerator:
- literals:
  - NATS_HOST=nats://nats:4222
  name: di-entry-config
