apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
resources:
- migrations.yaml
nameSuffix: "-latest" # {"$ref":"#/definitions/io.k8s.cli.substitutions.name-suffix"}
images:
- name: jasonblanchard/di-entry
  newTag: "latest" # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
configMapGenerator:
- name: entry-migrations-config
  namespace: di
  literals:
  - DB_USER=postgres
  - DB_PASSWORD=vault:secret/data/di-entry/production/app#DB_PASSWORD
  - DB_HOST=di-entry-psql
  - DB_PORT=5432
  - DB_DATABASE=di_entry
