apiVersion: batch/v1
kind: Job
metadata:
  name: di-entry-migrations
  namespace: di
spec:
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-entry
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      serviceAccountName: entry
      containers:
      - image: jasonblanchard/di-entry:latest
        name: di-entry-migrations
        command:
        - npm
        - run
        - db:migrate:up
        envFrom:
        - configMapRef:
            name: entry-migrations-config
      restartPolicy: Never
