apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphiql
  namespace: di
  labels:
    app: graphiql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphiql
  template:
    metadata:
      labels:
        app: graphiql
    spec:
      serviceAccountName: graphiql
      containers:
      - name: graphiql
        image: jasonblanchard/di-graphiql:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: graphiql-config
        # livenessProbe:
        #   httpGet:
        #     port: 8080
        #     path: /health
        # readinessProbe:
        #   httpGet:
        #     port: 8080
        #     path: /health
