apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authn
  name: authn
  namespace: di
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authn
  template:
    metadata:
      labels:
        app: authn
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-authn
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      serviceAccountName: authn
      containers:
      - image: jasonblanchard/di-authn:1cf026b3ed5a1a6972f45fab1116abf10e898720 # {"$ref":"#/definitions/io.k8s.cli.substitutions.image"}
        name: authn
        envFrom:
        - configMapRef:
            name: authn-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
        - containerPort: 8080
