apiVersion: getambassador.io/v1
kind: AuthService
metadata:
  name: authn-filter
spec:
  allowed_request_headers:
  - "CSRF-Token"
  auth_service: "authn:8080"
  failure_mode_allow: false
  include_body:
    allow_partial: true
    max_bytes: 4096
  path_prefix: "/session/authn"
  proto: http
  status_on_error:
    code: 503
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: authn
spec:
  service: authn:8080
  prefix: /api/authn/
  bypass_auth: true
  rewrite: '/'
