apiVersion: v1
kind: Service
metadata:
  name: authn
  namespace: di
  labels:
    app: authn
spec:
  type: ClusterIP
  selector:
    app: authn
  ports:
  - name: "8080"
    protocol: TCP
    port: 8080
    targetPort: 8080
