apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
resources:
- sa.yaml
- deployment.yaml
images:
- name: jasonblanchard/di-velocity
  newTag: latest
configMapGenerator:
- literals:
  - NATS_URL=nats://nats:4222
  name: velocity-config
