apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
commonLabels:
  environment: production
images:
- name: jasonblanchard/di-gql-edge
  newTag: 2c0c152c37ef5e498865b4e6d8025a7adc066b8e # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
