apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
commonLabels:
  environment: production
images:
- name: jasonblanchard/di-gql-edge
  newTag: 04a611a16613972a54fc85a0b78317635966abb2 # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
