apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
commonLabels:
  environment: production
images:
- name: jasonblanchard/di-gql-edge
  newTag: 531a67d98cb8c1d06fad6e53a1a73d5842d4e35f # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
