apiVersion: v1
kind: Service
metadata:
  name: graphiql
  namespace: di
  labels:
    app: graphiql
spec:
  type: ClusterIP
  selector:
    app: graphiql
  ports:
  - name: "8080"
    protocol: TCP
    port: 8080
    targetPort: 8080
