apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: di-production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: PLACEHOLDER.amazonaws.com # {"$openapi":"hostname"}
    http:
      paths:
      - backend:
          serviceName: ambassador
          servicePort: 80
        path: /
  - host: di.blanktech.net # {"$openapi":"domain"}
    http:
      paths:
      - backend:
          serviceName: ambassador
          servicePort: 80
        path: /
  tls:
  - hosts:
    - PLACEHOLDER.amazonaws.com # {"$openapi":"hostname"}
    secretName: instance-tls-secret
  - hosts:
    - di.blanktech.net # {"$openapi":"domain"}
    secretName: di-blanktech-net-tls-secret
