apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: di-production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-production"
spec:
  rules:
  - host: di.blanktech.net # {"$openapi":"domain"}
    http:
      paths:
      - backend:
          serviceName: ambassador
          servicePort: 80
        path: /
  tls:
  - hosts:
    - di.blanktech.net # {"$openapi":"domain"}
    secretName: di-blanktech-net-tls
