apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas: 1 # {"$ref":"#/definitions/io.k8s.cli.setters.replicas"}
bases:
- ../base
images:
- name: jasonblanchard/di-public-web:latest # {"$ref":"#/definitions/io.k8s.cli.substitutions.image"}
