apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-public-web
  newTag: 6230c828f0c904e39805fb4925e5461dd8484bbc # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
