apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: vault
spec:
  size: 1
  image: vault:1.3.1
  bankVaultsImage: banzaicloud/bank-vaults:latest
  caNamespaces: ["*"]
  serviceAccount: vault

  # Describe where you'd like to store the Vault unseal keys and root token.
  unsealConfig:
    # In this case we are storing the root token and the unseal keys in Kubernetes secrets.
    kubernetes:
      secretNamespace: vault

  # A YAML representation of the final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    api_addr: https://vault.vault:8200
    storage:
      file:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    ui: true
  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    policies:
      - name: "secret-admin"
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
          path "transit/keys/sanctum" {
            capabilities = ["read", "create", "update"]
          }
          path "transit/encrypt/sanctum" {
            capabilities = ["create", "update"]
          }
          path "transit/decrypt/sanctum" {
            capabilities = ["create", "update"]
          }
      - name: platform-test
        rules: |
          path "secret/data/platform-test/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: di-entry
        rules: |
          path "secret/data/di-entry/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: di-authn
        rules: |
          path "secret/data/di-authn/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: platform-test
            bound_service_account_names: ["platform-test"]
            bound_service_account_namespaces: ["platform-test"]
            policies: ["platform-test"]
            ttl: 1h
          - name: di-entry
            bound_service_account_names: ["di-entry", "di-entry-psql"]
            bound_service_account_namespaces: ["di"]
            policies: ["di-entry"]
            ttl: 1h
          - name: di-authn
            bound_service_account_names: ["authn"]
            bound_service_account_namespaces: ["di"]
            policies: ["di-authn"]
            ttl: 1h
      - type: github
        config:
          organization: aboutblanktech
        map:
          users:
            jasonblanchard: 'secret-admin'
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
      - path: transit
        type: transit
        description: Transit keys for sanctum.
    startupSecrets:
      - type: kv
        path: secret/data/platform-test/test
        data:
          data:
            TEST_SECRET: this-is-a-s3kr3t
  volumes:
    - name: vault-file
      persistentVolumeClaim:
        claimName: vault-file
  volumeMounts:
    - name: vault-file
      mountPath: /vault/file
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file
spec:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-file
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /vault/file
