apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: vault
spec:
  size: 1
  image: vault:1.3.1
  bankVaultsImage: banzaicloud/bank-vaults:latest
  caNamespaces: ["*"]
  serviceAccount: vault

  unsealConfig:
    aws:
      kmsKeyId: "ecef89bd-a051-49b3-9ee6-84540c3ca6c3"
      kmsRegion: "us-east-1"
      s3Bucket: "di-vault-backend"
      s3Prefix: "unseal/"
      s3Region: "us-east-1"

  # A YAML representation of the final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    api_addr: https://vault.vault:8200
    storage:
      s3:
        region: "us-east-1"
        bucket: "di-vault-backend"
        path: "secrets"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    ui: true
  credentialsConfig:
    env: AWS_SHARED_CREDENTIALS_FILE
    path: /etc/aws/credentials
    secretName: aws-cred
  externalConfig:
    policies:
      - name: "secret-admin"
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
          path "transit/keys/sanctum" {
            capabilities = ["read", "create", "update"]
          }
          path "transit/encrypt/sanctum" {
            capabilities = ["create", "update"]
          }
          path "transit/decrypt/sanctum" {
            capabilities = ["create", "update"]
          }
      - name: platform-test
        rules: |
          path "secret/data/platform-test/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: di-entry
        rules: |
          path "secret/data/di-entry/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: di-authn
        rules: |
          path "secret/data/di-authn/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: platform-test
            bound_service_account_names: ["platform-test"]
            bound_service_account_namespaces: ["platform-test"]
            policies: ["platform-test"]
            ttl: 1h
          - name: di-entry
            bound_service_account_names: ["entry", "entry-psql"]
            bound_service_account_namespaces: ["di"]
            policies: ["di-entry"]
            ttl: 1h
          - name: di-authn
            bound_service_account_names: ["authn"]
            bound_service_account_namespaces: ["di"]
            policies: ["di-authn"]
            ttl: 1h
      - type: github
        config:
          organization: aboutblanktech
        map:
          users:
            jasonblanchard: 'secret-admin'
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
      - path: transit
        type: transit
        description: Transit keys for sanctum.
    startupSecrets:
      - type: kv
        path: secret/data/platform-test/test
        data:
          data:
            TEST_SECRET: this-is-a-s3kr3t
