apiVersion: v1
kind: Service
metadata:
  labels:
    app: entry-gql-edge
  name: entry-gql-edge
  namespace: di
spec:
  ports:
  - name: "4000"
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: entry-gql-edge
  type: ClusterIP
