apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-workspace-web
  newTag: bc6b3a8fb01f78bad6d2259908de766b042c1b9a # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
