apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-workspace-web
  newTag: 2124c75fe01eb4a1f7dc12ba4317dc25ec7843df # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
