apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-workspace-web
  newTag: 98ded66ad2068440f081027adaae6e23300e52a8 # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
