apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-workspace-web
  newTag: 2b6d9bdda3c50f79847949122278232cd47353e5 # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
