apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-workspace-web
  newTag: 32bfe8f30f2bdadef82ee2195cb898f129d47422 # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
