apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-workspace-web
  newTag: 30c0dd49cd51e416a3275a6275de68d52194c462 # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
