apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: jasonblanchard/di-workspace-web
  newTag: a8f70d7823aa53bfe9427ddc26db55e52d80f627 # {"$ref":"#/definitions/io.k8s.cli.setters.tag"}
