apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-web
  namespace: di
  labels:
    app: workspace-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace-web
  template:
    metadata:
      labels:
        app: workspace-web
    spec:
      serviceAccountName: workspace-web
      containers:
      - name: workspace-web
        image: jasonblanchard/di-workspace-web:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: workspace-web-config
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
