namespace: di
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sa.yaml
- deployment.yaml
- service.yaml
- mapping.yaml
configMapGenerator:
- name: workspace-web-config
  literals:
  - PORT=8080
  - JS_MANIFEST_KEY='app.js'
  - BASE_PATH='/workspace/'
  - PAGE_TITLE='Workspace'
  - APP_CONTAINER_ID='app'
images:
- name: jasonblanchard/di-workspace-web
  newTag: latest
